services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - lgtm-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    networks:
      - lgtm-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - lgtm-network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"   # tempo-query
      - "4317:4317"   # OTLP gRPC
    networks:
      - lgtm-network

  mimir:
    image: grafana/mimir:latest
    command: [ "-config.file=/etc/mimir/config.yaml" ]
    volumes:
      - ./mimir-config.yaml:/etc/mimir/config.yaml
    ports:
      - "9009:9009"
    networks:
      - lgtm-network

networks:
  lgtm-network:
    driver: bridge