auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-04-01
      object_store: filesystem
      store: tsdb
      schema: v13
      index:
        prefix: index_
        period: 24h
ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  ingestion_rate_strategy: global  # Added this line
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_global_streams_per_user: 5000
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  creation_grace_period: 10m
  max_cache_freshness_per_query: 10m
  per_stream_rate_limit: 3MB  # Added this line
  per_stream_rate_limit_burst: 15MB  # Added this line

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m
  delete_request_store: filesystem
  retention_enabled: true
  retention_delete_delay: 48h
  retention_delete_worker_count: 150

analytics:
  reporting_enabled: false