global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mimir"
    static_configs:
      - targets: ["mimir:8080"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]

remote_write:
  - url: "http://mimir:8080/api/v1/push"